apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-core-fiap-deployment
  labels:
    app: vehicle-core-fiap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-core-fiap
  template:
    metadata:
      labels:
        app: vehicle-core-fiap
    spec:
      containers:
        - name: vehicle-core-fiap
          image: 202909432785.dkr.ecr.us-east-1.amazonaws.com/ms-vehicle-core-service:${GITHUB_SHA}
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: DATASOURCE_URL
              value: "jdbc:postgresql://database.ctkuimy64klv.us-east-1.rds.amazonaws.com:5432/"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: AWS_REGION
              value: "us-east-1"



          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
